---
- name: Provision an EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning
  vars:
    instance_type: t2.micro
    security_group: ansible-splunk
    image: ami-82be18ed
    keypair: id_rsa
    region: eu-central-1
    count: 1
    ec2tag: splunk
    inventory_group: splunk
  roles:
    - ansible-ec2-instance

- name: Installing and configuration of the Splunk Service
  hosts: splunk
  become: true
  remote_user: ec2-user
  vars:
    splunk_binary_url: https://s3.eu-central-1.amazonaws.com/mysplunk/splunk-7.1.1-8f0ead9ec3db-linux-2.6-x86_64.rpm
    splunk_binary_file: splunk-7.1.1-8f0ead9ec3db-linux-2.6-x86_64.rpm
    splunk_binary_sha256sum: 304f01f07fb7a9199337aac97bbc918c09f0829b5ffe8386d2b7758be3a6aa27
    splunk_pgp_public_key: http://docs.splunk.com/images/6/6b/SplunkPGPKey.pub
    splunk_host_domain:
    splunk_license_master:
    company: it-kombinat
    splunk_admin_passwd: demo0815  # Password must contain at least 8 total printable ASCII character(s)
  roles:
    - ansible-splunk-base

- name: Provision an EC2 Instance for RSYSLOG Client
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    instance_type: t2.micro
    security_group: splunk-client
    image: ami-7c4f7097
    keypair: id_rsa
    region: eu-central-1
    count: 3
    ec2tag: rsyslog-client
    inventory_group: rsyslog-clients
  roles:
    - ansible-ec2-instance

- name: Configuration of RSYSLOG - Client
  hosts: rsyslog-clients
  become: true
  remote_user: ec2-user
  vars:
    rsyslog_remote: "{{ groups['splunk'] }}"
  roles:
    - ansible-role-rsyslog
