---
- name: Provision an EC2 Instance for Splunk
  hosts: localhost
  connection: local
  gather_facts: False
  tags: ec2-splunk,splunk
  vars:
    instance_type: t2.micro
    security_group: ansible-splunk
    image: ami-7c4f7097 # ami-432e2fa8 CIS Amazon Linux Benchmark v2.0.0 - Level 1 - for further testing
    keypair: id_rsa
    region: eu-central-1
    count: 1
    ec2tag: splunk-docker
    inventory_group: splunk
  roles:
    - ansible-ec2-instance

- name: Installing Splunk Service as Container - Onboarding rsyslog and hec clients
  hosts: splunk
  become: true
  remote_user: ec2-user
  tags: splunk-vm,splunk
#  vars:
#    spl_container_name: splunk-demo
#    syslog_gen_service: false
#    spl_docker_image: stackware/spl:2.5
#    hec_token: dfsfsd-dsfds-sdfsf-43243
#    collector_container_name: collectorfordocker
#    collector_image: outcoldsolutions/collectorfordocker:3.0.93.180531
#    syslog_gen_syslog: syslog-gen-rsyslog  
#    syslog_gen_hec: syslog-gen-hec
#    syslog_gen_image: stackware/sysgen:1.6
#    syslog_gen_syslog: true
#    rsyslog_remote: "{{ groups['splunk'] }}"
#    syslog_gen_syslog: false
  pre_tasks:
    - name: Configure password Authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'
      register: configsshd

    - name: restart SSHD Service
      service:
        name: sshd
        state: restarted
      when: configsshd.changed
  roles:
   # - ansible-role-rsyslog
    - ansible-docker-spl
    - docker-collector
    - syslog-gen-docker

- name: Configure Callback-Plugin
  hosts: localhost
  tags: plugin
  vars:
    hec_token: dfsfsd-dsfds-sdfsf-43243
    rsyslog_remote: http://{{ groups['splunk'][0] }}:8088/services/collector/event"
  tasks:
    - name: Enabling Callback-Plugin
      ini_file:
        path: ~/ansible/splunk-demo/ansible.cfg
        section: default
        option: callback_whitelist
        value: splunk
        backup: yes

    - name: Configure RSYSLOG for Callback Plugin
      ini_file:
        path: ~/ansible/splunk-demo/ansible.cfg
        section: callback_splunk
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      loop:
        - { option: 'url', value: "{{ rsyslog_remote }}" }
        - { option: 'authtoken', value: "{{ hec_token }}" }

- name: Provision an EC2 Instance for SNORT
  hosts: localhost
  connection: local
  gather_facts: False
  tags: ec2-snort
  vars:
    instance_type: t2.micro
    security_group: ansible-splunk
    image: ami-7c4f7097 # ami-432e2fa8 CIS Amazon Linux Benchmark v2.0.0 - Level 1 - for further testing
    keypair: id_rsa
    region: eu-central-1
    count: 1
    ec2tag: snort-ids
    inventory_group: snort
  roles:
    - ansible-ec2-instance

- name: Installing Snort and Docker Collector
  hosts: snort
  become: true
  remote_user: ec2-user
  tags: snort
  vars:
    rsyslog_remote: "{{ groups['splunk'] }}"
    snort_forwarder: "{{ groups['splunk'] }}"
    hec_token: dfsfsd-dsfds-sdfsf-43243
  pre_tasks:
    - name: Configure password Authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'
      register: configsshd

    - name: restart SSHD Service
      service:
        name: sshd
        state: restarted
      when: configsshd.changed
  roles:
    - ansible-snort
#    - ansible-httpd-demo

- name: Provision an EC2 Instance for Badguy
  hosts: localhost
  connection: local
  gather_facts: False
  tags: ec2
  vars:
    instance_type: t2.micro
    security_group: ansible-splunk
    image: ami-7c4f7097 # ami-432e2fa8 CIS Amazon Linux Benchmark v2.0.0 - Level 1 - for further testing
    keypair: id_rsa
    region: eu-central-1
    count: 1
    ec2tag: badguy
    inventory_group: badguy
  roles:
    - ansible-ec2-instance

- name: Rollout Badguy
  hosts: badguy
  become: true
  remote_user: ec2-user
  tags: badguy
  vars:
    rsyslog_remote: "{{ groups['splunk'] }}"
    syslog_gen_service: false
    badguytgt: "{{ groups['snort'] }}"
    hec_token: dfsfsd-dsfds-sdfsf-43243
    collector_container_name: collectorfordocker
    collector_image: outcoldsolutions/collectorfordocker:3.0.93.180531
#  pre_tasks:
#    - name: Configure password Authentication
#      lineinfile:
#          dest: /etc/ssh/sshd_config
#          regexp: '^PasswordAuthentication'
#          line: 'PasswordAuthentication yes'
#      register: configsshd

#   - name: restart SSHD Service
#      service:
#        name: sshd
#        state: restarted
#      when: configsshd.changed
  roles:
    - ansible-badguy
    - docker-collector
