---
- name: Provision an EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: False
  tags: ec2
  vars:
    instance_type: t2.micro
    security_group: ansible-splunk
    image: ami-7c4f7097 # ami-432e2fa8 CIS Amazon Linux Benchmark v2.0.0 - Level 1
    keypair: id_rsa
    region: eu-central-1
    count: 1
    ec2tag: splunk-docker
    inventory_group: splunk
  roles:
    - ansible-ec2-instance

- name: Installing and configuration of the Splunk Service and Configure Rsyslog - Client --- ALL-IN-ONE --
  hosts: splunk
  become: true
  remote_user: ec2-user
  tags: docker
  vars:
    spl_container_name: splunk-demo
    spl_docker_image: stackware/spl:1.9
    hec_token: dfsfsd-dsfds-sdfsf-43243
    collector_container_name: collectorfordocker
    collector_image: outcoldsolutions/collectorfordocker:3.0.93.180531
    syslog_gen_syslog: syslog-gen-rsyslog  
    syslog_gen_hec: syslog-gen-hec
    syslog_gen_image: stackware/sysgen:1.6
    syslog_gen_syslog: true
    SPLURL: "{{ groups['splunk'] }}"
    rsyslog_remote: "{{ groups['splunk'] }}"
  roles:
    - ansible-docker-spl
    - docker-collector
    - syslog-gen-docker
   # - ansible-role-rsyslog
